### ISSUE TITLE
Aggregated column cannot have the same name as the underlying column in GroupedTableAppenderResponse

### ISSUE THREAD

**Issue by zikato** [spaghettidba/XESmartTarget#13]
If I take the example from the documentation and name the aggregate and underlying column same name

 `"MIN(collection_time AS collection_time"`

Full json
```
{
    "Target": {
        "ServerName": "MyServer",
        "SessionName": "loginaudit",
        "FailOnProcessingError": false,
        "Responses": [
            {
                "__type": "GroupedTableAppenderResponse",
                "ServerName": "MyServer",
                "DatabaseName": "xedemo",
                "TableName": "loginaudit",
                "AutoCreateTargetTable": true,
                "UploadIntervalSeconds": 10,
                "Events": [
                    "login"
                ],
                "OutputColumns": [
                    "database_name",
                    "MIN(collection_time) AS collection_time"
                ]
            }
        ]
    }
}

```

It will show an error

> Error - XESmartTarget.Core.Responses.TableAppenderResponse : Error uploading to the target table
> Error - XESmartTarget.Core.Responses.TableAppenderResponse : System.NullReferenceException: Object reference not set to an instance of an object.
>    at XESmartTarget.Core.Responses.GroupedTableAppenderResponse.Upload()
>    at XESmartTarget.Core.Responses.TableAppenderResponse.UploadTaskMain()

Might be worth mentioning that in the documentation. It took me a while to find the problem.

**Comment by spaghettidba** [comment]
Thanks! It's mentioned in [this blog post](https://spaghettidba.com/2022/02/28/recipe-6-auditing-successful-logins/) but not in the documentation.
I'll make sure to add it!
