### ISSUE TITLE
Column 'X' does not belong to underlying table 'events'

### ISSUE THREAD

**Issue by zikato** [spaghettidba/XESmartTarget#14]
I have a peculiar problem. I'm tracking an event and collecting the `sql_text` global field/action.
But when the event has column `is_system = true` then sql_text is not collected at all (the schema shape has changed)

![image](https://user-images.githubusercontent.com/24471797/156526192-fe897c51-e88e-43c7-b8c5-89a07da8bc5d.png)

Service Broker activation is considered a system process even though it's arguably a user process.

I propose that the XESmartTarget return a NULL when the column is not found instead of the error. The SSMS XE viewer acts the same.

I've also tried to split the collection into two responses - one where `is_system = 'False'` collects the sql_text and the other one which doesn't. My filter snippet looks like this:

`"Filter": "query_hash_signed <> 0 OR is_system = 'True'"`

Then I've got an error:

> Error - XESmartTarget.Core.Target : servername
> Error - XESmartTarget.Core.Target : Cannot find column [is_system].
> Error - XESmartTarget.Core.Target :    at System.Data.NameNode.Bind(DataTable table, List`1 list)
>    at System.Data.BinaryNode.Bind(DataTable table, List`1 list)
>    at System.Data.DataExpression.Bind(DataTable table)
>    at System.Data.DataView.set_RowFilter(String value)
>    at XESmartTarget.Core.Utils.XEventDataTableAdapter.ReadEvent(PublishedEvent evt) in C:\github\XESmartTarget\XESmartTarget.Core\Utils\XEventDataTableAdapter.cs:line 242
>    at XESmartTarget.Core.Responses.TableAppenderResponse.Enqueue(PublishedEvent evt) in C:\github\XESmartTarget\XESmartTarget.Core\Responses\TableAppenderResponse.cs:line 130
>    at XESmartTarget.Core.Target.TargetWorker.Process() in C:\github\XESmartTarget\XESmartTarget.Core\Target.cs:line 158

This is weird because the column is definitely there.
The column is recognized when I set up a different XE with a different JSON.

**Comment by spaghettidba** [comment]
Hi Tom, thanks for reporting the issue.
Regarding the possibility to return NULL when the column is missing, I'm quite skeptic. The data type of the column is based on the data type of the underlying field/action, so I would have nothing base the choice on.
Maybe I can work on a solution if I have an example.
Could you please share the session script and json file you used?

**Comment by zikato** [comment]
I've found the problem with the `Cannot find column [is_system].` The column has to be in the `OutputColumns` section to be recognized even though I only use it for filtering.

I can share the session and json, but the XE data will be hard to reproduce. It monitors Linked server calls through a Service Broker activation.

**Comment by spaghettidba** [comment]
Thanks! I'll have a look as soon as possible (might take a while...)

**Comment by zikato** [comment]
I've tested and this version I've shared works. It filters out the correct rows with the is_system and doesn't try to access the missing sql_text

**Comment by spaghettidba** [comment]
Huh, sorry, which version?

**Comment by zikato** [comment]
According to GitHub - Latest 1.4.5 (downloaded yesterday). 
Even though I'm not sure how to check it on the installed version

**Comment by zikato** [comment]
Sorry, it was probably confusing.
I only had the 1.4.5 version.
So filtering requires the column to be on the output (that was mistake on my part)
As for the sql_text - the problem is that non-system XE rows have that column and system XE rows don't have it.

I thought maybe doing filter on the is_system and splitting it into two responses could get around that. But the events table check is probably before the filter check. It still fails.

The only workaround I can think of is to split my Extended event into two session (one for system and one without)

**Comment by zikato** [comment]
Ok, I had another wrong assumption. 
is_system show either True or False in the SSMS or export, but it really is 1 or 0 respectively. 

Updating my filter to `is_system = 0` helped.

I think the issue can be closed as there is a workaround by using several responses with the relevant filter.

**Comment by zikato** [comment]
Update: Sadly it's not fixed for me. For some events, the sql_text is just not collected and I can't see any pattern explaining why.

You said the data type is based on the underlying field.
Would it be possible to always map the global fields? They should have static data types and when the underlying data isn't there a NULL can be passed.
