### ISSUE TITLE
XelToCsv won't launch 1.4.9

### ISSUE THREAD

**Issue by mdumdei** [spaghettidba/XESmartTarget#22]
In 1.4.9, the XelToCsv doesn't run:
C:\Program Files\XESmartTarget>XelToCsv.exe

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'CommandLine, Version=1.9.71.2, Culture=neutral, PublicKeyToken=de6f01bd326f8c32' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at XelToCsv.Program.Main(String[] args)

XESmartTarget is using version 2.8.0 of the CommandLine package. I think it is causing GAC issues with the mismatch??

**Comment by IanMoroney** [comment]
@spaghettidba , i'm also getting exactly the same issue after installing 1.5.3 on windows.
I tried doing a regsvr32 on CommandLine.dll to see if it was that, but it looks like that dll doesn't need registering.

Any ideas how to solve this problem? I'm unable to run XelToCsv.exe

I added the XESmartTarget folder to the PATH.

**Comment by spaghettidba** [comment]
OK, I have a new release that should fix that. Sorry it took me this long
https://github.com/spaghettidba/XESmartTarget/releases/tag/v1.5.4

**Comment by mdumdei** [comment]
Thanks - have not had time to try it yet, but should next week.

**Comment by IanMoroney** [comment]
```
Info - XelToCsv.Program : XelToCsv, Version=1.5.4.0, Culture=neutral, PublicKeyToken=null 1.5.4
Info - XelToCsv.Program : Converting https://storageaccount.blob.core.windows.net/sqldbauditlogs/servername/databasename/SqlDbAuditing_ServerAudit/2023-06-32/32_36_32_254_56.xel to test22.csv
Error - XelToCsv.Program : Conversion Error
Error - XelToCsv.Program : System.ArgumentException: filename
   at Microsoft.SqlServer.XEvent.Linq.Internal.XEventFileReaderMessageHandler.NotifyInvalidParameter(XEventFileReaderMessageHandler* , UInt16* paramName, UInt64 value)
   at XE_FileReader<XE_FileReaderDefaultPolicy>.SetIsSequentialScan(XE_FileReader<XE_FileReaderDefaultPolicy>* , Int32 )   at Microsoft.SqlServer.XEvent.Linq.Internal.XEventInteropFileReader..ctor(String[] fileList, String[] mdFiles)
   at Microsoft.SqlServer.XEvent.Linq.XEventFileProvider`1..ctor(QueryableXEventData queryable, String[] fileList, String[] metadataFiles)
   at Microsoft.SqlServer.XEvent.Linq.QueryableXEventData..ctor(String fileName)
   at XESmartTarget.Core.Utils.XELFileCSVAdapter.Convert() in C:\GitHub\XESmartTarget\XESmartTarget.Core\Utils\XELFileCSVAdapter.cs:line 34
   at XelToCsv.Program.Convert(String sourceFile, String destinationFile) in C:\GitHub\XESmartTarget\XelToCsv\Program.cs:line 56
Info - XelToCsv.Program : Conversion finished at 12/06/2023 10:51:50
Info - XelToCsv.Program : 0.1550185 seconds taken
```

I'd expect that the response being given to XelToCsv.exe is:

```
<?xml
version="1.0" encoding="utf-8"?>
<Error>
    <Code>PublicAccessNotPermitted</Code>
    <Message>Public access is not permitted on this storage account.
RequestId:7c0fa3c6-d99f-4c31-993c-5325dba89ad9
Time:2023-06-12T09:55:42.0066658Z</Message>
</Error>
```

but maybe it's not handling that response correctly?

**Comment by IanMoroney** [comment]
When run on a local file, it worked fine this time:

```
xeltocsv -s testfile.xel -d test23.csv
Info - XelToCsv.Program : XelToCsv, Version=1.5.4.0, Culture=neutral, PublicKeyToken=null 1.5.4
Info - XelToCsv.Program : Converting testfile.xel to test23.csv
Info - XelToCsv.Program : Conversion finished at 12/06/2023 10:58:26
Info - XelToCsv.Program : 2.6795824 seconds taken
```

**Comment by spaghettidba** [comment]
Hey, thanks for the feedback! I don't think XelToCsv can read a file on a blob storage directly, I'm afraid you will have to download it first. Sorry about  that
