### ISSUE TITLE
Error during start: Could not load file or assembly 'Microsoft.SqlServer.XEvent.Linq.dll' or one of its dependencies. 

### ISSUE THREAD

**Issue by andb24** [spaghettidba/XESmartTarget#26]
Please help how to fix this error:
MSSQL 2019, Win server 2016 or 2019

```
D:\XEVENTS>sp_trace.bat

D:\XEVENTS>"C:\Program Files\XESmartTarget\xesmarttarget.exe" --File d:\xevents\sp_trace.json --GlobalVariables ServerName=sqlnonerp4
XESmartTarget 1.5.1
Copyright c 2018 spaghettidba - spaghettidba

Info - XESmartTarget.Program : Reading configuration from 'd:\xevents\sp_trace.json'
Info - XESmartTarget.Core.Responses.TableAppenderResponse : Initializing Response of Type 'XESmartTarget.Core.Responses.TableAppenderResponse'
Info - XESmartTarget.Program : Starting Target
Error - XESmartTarget.Core.Target : System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: 
Could not load file or assembly 
'Microsoft.SqlServer.XEvent.Linq.dll' or one of its dependencies. 
The specified module could not be found.
   at XESmartTarget.Core.Target.TargetWorker.Process()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at XESmartTarget.Core.Target.Start() in C:\github\XESmartTarget\XESmartTarget.Core\Target.cs:line 64
---> (Inner Exception #0) System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.SqlServer.XEvent.Linq.dll' or one of its dependencies. 
The specified module could not be found.
File name: 'Microsoft.SqlServer.XEvent.Linq.dll'
   at XESmartTarget.Core.Target.TargetWorker.Process()
   at System.Threading.Tasks.Task.Execute()


```

**Comment by spaghettidba** [comment]
Is [Microsoft Visual C++ 2013 Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=40784) installed?
