### ISSUE TITLE
Error: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Zhunya** [spaghettidba/XESmartTarget#6]
Latest Version

Config

```JSON
{
    "Target": {
        "ServerName": "<SQLInstance>",
        "SessionName": "DDL Events in test_lk",
        "Responses": [
            {
                "__type": "TableAppenderResponse",
                "ServerName": "<SQLInstance>",
                "DatabaseName": "test_data_base",
                "TableName": "ddlAuditEvents",
                "AutoCreateTargetTable": true,
                "UploadIntervalSeconds": 10,
                "Events": [
                    "object_altered",
                    "object_created",
                    "object_deleted"
                ],
                "OutputColumns": [
                    "timestamp",
                    "username",
                    "object_name",
                    "name",
                    "ddl_phase"
                ]
            }
        ]
    }
}
```

Error:

```powershell
Info - XESmartTarget.Core.Responses.TableAppenderResponse : Creating target table UK-SQL01.test_uk_octopus.ddlAuditEvent
s
Error - XESmartTarget.Core.Target : System.NullReferenceException: Object reference not set to an instance of an object.

   at XESmartTarget.Core.Utils.DataTableTSQLAdapter.GetCreateFromDataTableSQL() in C:\GitHub\XESmartTarget\XESmartTarget.Core\Utils\DataTableTSQLAdapter.cs:line 214
   at XESmartTarget.Core.Utils.DataTableTSQLAdapter.CreateFromDataTable() in C:\GitHub\XESmartTarget\XESmartTarget.Core\Utils\DataTableTSQLAdapter.cs:line 132
   at XESmartTarget.Core.Responses.TableAppenderResponse.CreateTargetTable(DataTable data) in C:\GitHub\XESmartTarget\XESmartTarget.Core\Responses\TableAppenderResponse.cs:line 220
   at XESmartTarget.Core.Responses.TableAppenderResponse.StartUploadTask() in C:\GitHub\XESmartTarget\XESmartTarget.Core\Responses\TableAppenderResponse.cs:line 145
   at XESmartTarget.Core.Responses.TableAppenderResponse.Enqueue(PublishedEvent evt) in C:\GitHub\XESmartTarget\XESmartTarget.Core\Responses\TableAppenderResponse.cs:line 133
   at XESmartTarget.Core.Target.Start() in C:\GitHub\XESmartTarget\XESmartTarget.Core\Target.cs:line 94
```
Table is not created.

**Comment by spaghettidba** [comment]
Try this pre-release and tell me if it works
[XESmartTarget_x64.zip](https://github.com/spaghettidba/XESmartTarget/files/3446481/XESmartTarget_x64.zip)

**Comment by Zhunya** [comment]
Error gone, thank you!
